### ISSUE TITLE
Count Pin of Artnet encode missing from Gamma

### ISSUE THREAD

**Issue by YanYas** [vvvv/VL.IO.ArtNet#1]
Hi,

When I use the artnet send node in vvv I can set the universe size with the _count_ pin. Its missing from the gamma nodes and I need it with PixLite artnet devices.

![image](https://user-images.githubusercontent.com/9497052/147254872-5279aed7-a782-488b-a541-c28c9857f6c1.png)

![image](https://user-images.githubusercontent.com/9497052/147254937-1390ac07-817f-4a1b-9ec3-f8dfe7762fa7.png)

**Comment by joreg** [comment]
sorry for the late reply. this is now fixed in latest vvvv gamma 5.3 previews. the count pin is not needed here because the count is now taken from the value spread.
